<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class WPSB_Backup_Security {

    /**
     * Allowed backup component types.
     */
    private static $allowed_types = array( 'database', 'files', 'posts', 'plugins' );

    /**
     * Verify a WordPress nonce. Dies with JSON error on failure.
     *
     * @param string $nonce  The nonce value to verify.
     * @param string $action The nonce action name.
     */
    public static function verify_nonce( $nonce, $action ) {
        if ( ! wp_verify_nonce( $nonce, $action ) ) {
            wp_send_json_error( array( 'message' => 'Security check failed.' ), 403 );
        }
    }

    /**
     * Check that the current user has manage_options capability. Dies on failure.
     */
    public static function check_capability() {
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_send_json_error( array( 'message' => 'Permission denied.' ), 403 );
        }
    }

    /**
     * Validate a backup component type against the allowlist.
     *
     * @param  string $type Raw type string.
     * @return string|false Sanitized type or false if invalid.
     */
    public static function sanitize_backup_type( $type ) {
        $type = sanitize_key( $type );
        if ( in_array( $type, self::$allowed_types, true ) ) {
            return $type;
        }
        return false;
    }

    /**
     * Sanitize an array of backup component types.
     *
     * @param  array $types Raw array from user input.
     * @return array        Only valid types.
     */
    public static function sanitize_components( $types ) {
        if ( ! is_array( $types ) ) {
            return array();
        }
        $clean = array();
        foreach ( $types as $type ) {
            $sanitized = self::sanitize_backup_type( $type );
            if ( false !== $sanitized ) {
                $clean[] = $sanitized;
            }
        }
        return array_unique( $clean );
    }

    /**
     * Validate a backup_id string.
     * IDs are generated by uniqid('wpsb_', true) so they look like wpsb_6123abc.def456
     *
     * @param  string $id Raw backup ID.
     * @return string|false Sanitized ID or false if invalid.
     */
    public static function sanitize_backup_id( $id ) {
        $id = sanitize_text_field( $id );
        if ( preg_match( '/^wpsb_[a-zA-Z0-9_.]+$/', $id ) ) {
            return $id;
        }
        return false;
    }

    /**
     * Ensure a resolved filesystem path stays within ABSPATH (prevent path traversal).
     *
     * @param  string $path Filesystem path to check.
     * @return string|false Real path or false if outside ABSPATH.
     */
    public static function sanitize_path( $path ) {
        $real = realpath( $path );
        if ( false === $real ) {
            return false;
        }
        $abspath = realpath( ABSPATH );
        if ( false === $abspath ) {
            return false;
        }
        if ( strpos( $real, $abspath ) !== 0 ) {
            return false;
        }
        return $real;
    }
}
